/*
  Book data — kept entirely separate from presentation.
  Adding a book means adding an entry here; the shelf renders itself.

  cover / accent are the only "design" fields, standing in for real cover
  art: a dominant color pulled from the jacket, and a legible text color
  to sit on top of it.

  Optional: `image: "./assets/books/<id>.jpg"` puts the real jacket on the
  front board (the spine still uses `cover`). Notes may run to several
  paragraphs — separate them with a blank line ("\n\n").
*/

window.BOOKS = [
  // ---------------------------------------------------------------- 2026
  {
    id: "hyperion",
    title: "Hyperion",
    author: "Dan Simmons",
    year: 2026,
    dateRead: "2026-01-03",
    rating: 4,
    pages: 481,
    genre: "Science Fiction",
    notes:
      "An interesting mystery through the lens of multiple different characters. Some of the characters' stories were incredibly well written and I couldn't stop turning the pages while other characters were more of a slog. Definitely an interesting take on a book that I haven't seen before. I'm very excited to read the next ones in the series.",
    favorite: false,
    cover: "#6b4630",
    accent: "#f3ede1",
  },
  {
    id: "dungeon-crawler-carl",
    title: "Dungeon Crawler Carl",
    author: "Matt Dinniman",
    year: 2026,
    dateRead: "2026-01-05",
    rating: 4,
    pages: 466,
    genre: "LitRPG",
    notes:
      "The Hitchhiker's Guide to the Galaxy meets an RPG. A very funny book that keeps you engaged through the whole read. While the writing by Matt Dinniman isn't the strongest he kept me wanting to know what happens next the whole book.",
    favorite: true,
    cover: "#563a4b",
    accent: "#f3ede1",
  },
  {
    id: "carl-s-doomsday-scenario",
    title: "Carl’s Doomsday Scenario",
    author: "Matt Dinniman",
    year: 2026,
    dateRead: "2026-01-08",
    rating: 4,
    pages: 379,
    genre: "LitRPG",
    notes:
      "The antics from book one continue on in book two. This series remains charming, while the mystery of what is happening behind the scenes only grows. The video game aspects of the series get more and more interesting in the second novel in the series. Again I can't wait to see what happens next.",
    favorite: true,
    cover: "#2f4f4a",
    accent: "#f3ede1",
  },
  {
    id: "what-i-talk-about-when-i-talk-about-running",
    title: "What I Talk About When I Talk About Running",
    author: "Haruki Murakami",
    year: 2026,
    dateRead: "2026-01-15",
    rating: 4,
    pages: 192,
    genre: "Nonfiction",
    notes:
      "A wonderful and inspiring memoir. This is the first book I've read by Murakami and boy was it a treat. He speaks beautifully, I've never read a non-fiction book that I have enjoyed reading in this way, not just for the knowledge within the pages, but for the way in which it was written. No wonder Murakami has such a large following. I'm excited to read more by him.",
    favorite: true,
    cover: "#874f2c",
    accent: "#f3ede1",
  },
  {
    id: "tender-is-the-flesh",
    title: "Tender is the Flesh",
    author: "Agustina Bazterrica",
    year: 2026,
    dateRead: "2026-01-26",
    rating: 2,
    pages: 209,
    genre: "Horror",
    notes:
      "While I enjoyed my time with this book, I do find that it's very obvious the person who wrote it had found out about factory farming, turned vegan and wrote this novel. The ideas in it are very valid and I did enjoy my read, but I very much felt like the author was hitting me over the head with the message \"Eating Animals is BAD\". I would recommend it, only if you're looking to read something macabre for the sake of reading something macabre or if you would like to learn a little more about the horrors of factory farming.",
    favorite: false,
    cover: "#3a3f2f",
    accent: "#f3ede1",
  },
  {
    id: "the-dungeon-anarchist-s-cookbook",
    title: "The Dungeon Anarchist’s Cookbook",
    author: "Matt Dinniman",
    year: 2026,
    dateRead: "2026-02-03",
    rating: 3,
    pages: 534,
    genre: "LitRPG",
    notes:
      "When the author says \"I know this will be confusing, but don't worry there is a map later in the book that will help this all make sense later\" it turns out that's a bit of a red flag. This book was still entertaining, and I did have a good time reading it but man do you really get lost in what is happening in the plot and where the characters are at any given time. There are times in this book where locations and people are being listed off at such an unprecedented pace, my eyes started to gloss over. This was by far the weakest addition to the Dungeon Crawler series. That all being said, I did still enjoy the read and I'm excited to see what happens next.",
    favorite: false,
    cover: "#5a3a2a",
    accent: "#f3ede1",
  },
  {
    id: "kafka-on-the-shore",
    title: "Kafka on the Shore",
    author: "Haruki Murakami",
    year: 2026,
    dateRead: "2026-02-08",
    rating: 4,
    pages: 467,
    genre: "Literary Fiction",
    notes:
      "A beautifully written book about a boy's fantastic journey. Nothing in this book makes sense in the most beautiful way, from a boy talking to ghosts to a simpleton who can talk to cats. Some of this book was fantastic and whimsical and some of it was weird and disturbing. Murakami is obviously incredibly imaginative and quite the dreamer. He writes every scene so beautifully I wanted to be in every place he wrote about. Until that time that I'm unable to run away to a library in a small town and read all of my days away, I'll continue to dream that I can be in Murakami's worlds.",
    favorite: false,
    cover: "#8a3b2b",
    accent: "#f3ede1",
  },
  {
    id: "the-gate-of-the-feral-gods",
    title: "The Gate of the Feral Gods",
    author: "Matt Dinniman",
    year: 2026,
    dateRead: "2026-02-17",
    rating: 4,
    pages: 597,
    genre: "LitRPG",
    notes:
      "It seems like Matt Dinniman's writing is starting to improve officially in this book. I really want to play the game that this world is in. I continue to believe that it would make an incredible video game - though I guess that's the whole point - I also believe that it would be impossible to translate into a game. At least yet.",
    favorite: false,
    cover: "#2e3d2f",
    accent: "#f3ede1",
  },
  {
    id: "groundwork-of-the-metaphysics-of-morals",
    title: "Groundwork of the Metaphysics of Morals",
    author: "Immanuel Kant",
    year: 2026,
    dateRead: "2026-03-01",
    rating: 3,
    pages: 76,
    genre: "Philosophy",
    notes:
      "I'm not sure that I am fully sold on deontology. While Kant brings up some interesting ideas about the only true good being the idealistic true good, there really seems to be a flaw with excluding the real ramifications of that practice in the real world. In a fake ideal world, sure but in the world in which we live I don't believe that someone can completely live by this moral framework - though I do believe that you should strive to live by it.",
    favorite: false,
    cover: "#33475b",
    accent: "#f3ede1",
  },
  {
    id: "tokyo-ueno-station",
    title: "Tokyo Ueno Station",
    author: "Miri Yu",
    year: 2026,
    dateRead: "2026-03-10",
    rating: 3,
    pages: 168,
    genre: "Literary Fiction",
    notes:
      "A beautiful depiction of what it is like to be homeless and how someone has come into that situation. This book shows you a situation in which some people find themselves that seems so hard to believe yet so common in the world in which we live. The story of the protagonist is haunting, sad and yet still beautiful. While at times in this book there seemed to be poetry that was odd or out of place, I guess it sort of flows with the idea that we are looking through the eyes and into the mind of a ghost. Even though some of the book dragged and was hard to get through - I still found it very touching and an incredible look into the lives of others which I so seldom have the chance to view.",
    favorite: false,
    cover: "#b08a3e",
    accent: "#241c17",
  },
  {
    id: "leonardo-da-vinci",
    title: "Leonardo da Vinci",
    author: "Walter Isaacson",
    year: 2026,
    dateRead: "2026-04-03",
    rating: 4,
    pages: 599,
    genre: "Nonfiction",
    notes:
      "No wonder I have seen the name Walter Isaacson in so many places. It makes sense that he is such a prolific biographer. He studies and respects his subjects to such a high degree. You really get the sense of how impressed he is by Leonardo. After having heard so much about Da Vinci, it was interesting reading about him and seeing how human he truly was. His talents and dedication to his study are incredible but like all of us he has flaws. His seeming lack of either ability or interest to finish a project when he was working on something either because it became difficult or because he simply lost interest was fascinating. There are so many traits in him which make him so relatable to the everyday man, then you see what he was working on or just curious about and drawing in his spare time and you get a sense of how truly capable he was.",
    favorite: false,
    cover: "#4a5a35",
    accent: "#f3ede1",
  },
  {
    id: "the-butcher-s-masquerade",
    title: "The Butcher’s Masquerade",
    author: "Matt Dinniman",
    year: 2026,
    dateRead: "2026-04-10",
    rating: 4,
    pages: 726,
    genre: "LitRPG",
    notes:
      "He's been building up the hype for this edition in the series for several books now, and it's definitely a good one. I don't love how much he builds up the stuff that is still to come in the series so often. It distracts from what is currently happening for sure, at least he keeps the pace moving so fast that you almost forget that it's happening. Again there are some classic silly antics in this one and more tight situations that seem impossible to get out of but there's always a way.",
    favorite: false,
    cover: "#3c5a58",
    accent: "#f3ede1",
  },
  {
    id: "the-eye-of-the-bedlam-bride",
    title: "The Eye of the Bedlam Bride",
    author: "Matt Dinniman",
    year: 2026,
    dateRead: "2026-04-16",
    rating: 4,
    pages: 832,
    genre: "LitRPG",
    notes:
      "Oh he's so back with this one. As I read this book I almost felt like I was watching Yu-Gi-Oh again as a kid. I love a good card game and the mechanics behind it were very fun. I loved seeing the players try to break the game. Again Matt Dinniman's writing is probably the only thing holding this series back from being truly great. I've been saying this for a while about his books, they are the literary equivalent of a McDonald's burger; it isn't fine dining by any means but you're going to enjoy yourself and it is something you do look forward to.",
    favorite: false,
    cover: "#2a2724",
    accent: "#f3ede1",
  },
  {
    id: "the-inner-game-of-tennis",
    title: "The Inner Game of Tennis",
    author: "W. Timothy Gallwey",
    year: 2026,
    dateRead: "2026-04-26",
    rating: 4,
    pages: 141,
    genre: "Psychology",
    notes:
      "A phenomenal book that teaches you how to clear your mind and trust your body. This book applies to so much more than just tennis. I find myself coming back to this advice quite frequently, it helps me be more present and enjoy the process, whether that's sport or work or the rest of my life.",
    favorite: true,
    cover: "#5c2a34",
    accent: "#f3ede1",
  },
  {
    id: "this-inevitable-ruin",
    title: "This Inevitable Ruin",
    author: "Matt Dinniman",
    year: 2026,
    dateRead: "2026-05-10",
    rating: 4,
    pages: 880,
    genre: "LitRPG",
    notes:
      "This is one of the books that Matt Dinniman has been building up to for several books now. While this book is very long it does move incredibly quickly. So much happens it's hard to keep track of everything at this point. Some of my favourite parts about this series have started to die off though. I am starting to miss all of the stats and seeing the impact they have on the world. It really seems like Matt is trying to move away from that mattering at all at this point.",
    favorite: false,
    cover: "#35492f",
    accent: "#f3ede1",
  },
  {
    id: "a-parade-of-horribles",
    title: "A Parade of Horribles",
    author: "Matt Dinniman",
    year: 2026,
    dateRead: "2026-05-24",
    rating: 4,
    pages: 704,
    genre: "LitRPG",
    notes:
      "I have a lot of fun with some of the gimmicks in this series. This was one of those gimmicks that really sat well with me. The races and improving the vehicles over time really brought back that progression which I felt like I was missing in the last book in the series. I hope he continues to focus on that in the future.",
    favorite: false,
    cover: "#263349",
    accent: "#f3ede1",
  },
  {
    id: "suicide",
    title: "Suicide",
    author: "Édouard Levé",
    year: 2026,
    dateRead: "2026-05-31",
    rating: 5,
    pages: 123,
    genre: "Literary Fiction",
    notes:
      "A masterpiece. A beautifully devastating piece of literature. At times I felt as if I've felt so many of the same feelings and emotions the author describes - it's as if I was reading my own thoughts. The way in which the author seems to jump between stories of his friend and himself is haunting. I will never forget this book and I have told anyone who will listen about it.",
    favorite: true,
    cover: "#a15b4f",
    accent: "#241c17",
  },
  {
    id: "galapagos",
    title: "Galápagos",
    author: "Kurt Vonnegut",
    year: 2026,
    dateRead: "2026-06-07",
    rating: 4,
    pages: 295,
    genre: "Fiction",
    notes:
      "A hilarious book about a future which might have been. Vonnegut is always a worthwhile read, I always catch myself laughing out loud.",
    favorite: false,
    cover: "#9c7a2e",
    accent: "#241c17",
  },
  {
    id: "a-farewell-to-arms",
    title: "A Farewell to Arms",
    author: "Ernest Hemingway",
    year: 2026,
    dateRead: "2026-06-14",
    rating: 2,
    pages: 332,
    genre: "Fiction",
    notes:
      "My dad's going to be mad at me for this one, but honestly this was my first book by Hemingway and I was very underwhelmed. The prose was odd and the dialogue hard to follow. I can't say I was very invested in the characters either. What I will say is the ending of the book is terrific and honestly the book's only saving grace.",
    favorite: false,
    cover: "#7a4a52",
    accent: "#f3ede1",
  },
  {
    id: "the-picture-of-dorian-gray",
    title: "The Picture of Dorian Gray",
    author: "Oscar Wilde",
    year: 2026,
    dateRead: "2026-06-21",
    rating: 3,
    pages: 246,
    genre: "Horror",
    notes:
      "You can tell this book was written by a poet - and that's a good thing. I was a little sad however that a large part of Dorian's descent was just skipped over, I think I would have liked to see more of that evolution. It also seems to me that he was too easily convinced to become a bad person. Either way a very cool premise which I had a good time with.",
    favorite: false,
    cover: "#4d443c",
    accent: "#f3ede1",
  },
  {
    id: "the-colour-of-magic",
    title: "The Colour of Magic",
    author: "Terry Pratchett",
    year: 2026,
    dateRead: "2026-07-05",
    rating: 5,
    pages: 240,
    genre: "Fantasy",
    notes:
      "This book was very reminiscent of the Hitchhiker's Guide to the Galaxy for me. I love those books and I love this one as well. Very charming and funny. I feel like this book has everything that I could want in a fantasy book. Magic, dragons, guilds, gods and just plain randomness.",
    favorite: true,
    cover: "#2b2c4a",
    accent: "#f3ede1",
  },
  {
    id: "on-the-origin-of-species",
    title: "On the Origin of Species",
    author: "Charles Darwin",
    year: 2026,
    dateRead: "2026-07-19",
    rating: 4,
    pages: 502,
    genre: "Nonfiction",
    notes:
      "Very interesting to see where our modern understanding of evolution comes from. A man far ahead of his time. While the field of genetics didn't yet exist, he seems to have outlined how genetic traits get passed down through bloodlines. A truly inspiring read.",
    favorite: false,
    cover: "#3e4a52",
    accent: "#f3ede1",
  },
  {
    id: "the-dream-of-a-ridiculous-man",
    title: "The Dream of a Ridiculous Man",
    author: "Fyodor Dostoevsky",
    year: 2026,
    dateRead: "2026-07-22",
    rating: 4,
    pages: 120,
    genre: "Literary Fiction",
    notes:
      "A beautiful collection of short stories all about the human psyche. All of the \"villains\" in this book seem so real.",
    favorite: false,
    cover: "#8a3b2b",
    accent: "#f3ede1",
  },
  {
    id: "in-cold-blood",
    title: "In Cold Blood",
    author: "Truman Capote",
    year: 2026,
    dateRead: "2026-08-05",
    rating: 5,
    pages: 352,
    genre: "True Crime",
    notes:
      "Truman Capote is one hell of a writer. This is the first book of his that I've read and I want to read more. I couldn't get enough of this book. The chilling crimes of two individuals who seemed like they couldn't get out of the life of crime. Both always had other people to blame. This is an incredibly personal story about these men and the atrocity they committed told by a master storyteller.",
    favorite: true,
    cover: "#2e3d2f",
    accent: "#f3ede1",
  },
  {
    id: "the-book-of-disquiet",
    title: "The Book of Disquiet",
    author: "Fernando Pessoa",
    year: 2026,
    dateRead: "2026-08-26",
    rating: 3,
    pages: 472,
    genre: "Nonfiction",
    notes:
      "Poetic, insightful and sad. This book explores a man's soul, a man who it seems wanted to be a part of a different world, his dream world. While incredibly intelligent and well written it seems that the author of this book or at least his heteronyms are still wishing for something more - a real connection to life itself.",
    favorite: false,
    cover: "#33475b",
    accent: "#f3ede1",
  },
];
